import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { headers } from "next/headers";
import { type ReactNode } from "react";

import { cookieToInitialState } from "wagmi";
import "./globals.css";

import { getConfig } from "../lib/wagmi";
import { Providers } from "./providers";
import { generateJWT } from "../lib/generateJWT";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Wagmi",
  description: "Generated by create-wagmi",
};

export default async function RootLayout(props: { children: ReactNode }) {
  const jwt = await generateJWT();
  const initialState = cookieToInitialState(
    getConfig(jwt),
    headers().get("cookie")
  );

  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers initialState={initialState} jwt={jwt}>
          {props.children}
        </Providers>
      </body>
    </html>
  );
}
